spring.application.name=product-service

spring.data.mongodb.uri=mongodb://root:password@localhost:27017/product-service?authSource=admin

# Server Configuration
server.port=8084
server.servlet.context-path=/api

# Actuator Configuration
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

# Logging Configuration
logging.level.root=INFO
logging.level.com.orderly.product_service=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
